### PR TITLE
load now handles slices of irregularly sampled data

### PR DESCRIPTION
**Pull request by bendichter**

### CODE REVIEW

**Comment by apdavison** [comment]
Hi Ben, many thanks for the PR. Since this is a long-lived branch with multiple contributors, it would be better to make future PRs against the nwb2 branch on NeuralEnsemble/python-neo

**Comment by bendichter** [comment]
@apdavison ok, I was going based on [this PR](https://github.com/NeuralEnsemble/python-neo/pull/796). If we want to use another branch as the basis for feature development, perhaps we should open a PR with that branch and close this one.

**Comment by apdavison** [comment]
@bendichter that's a good point. Let me think about it, but probably opening a new PR is the best approach.

**Comment by bendichter** [comment]
@apdavison, sure, multi-person PRs can be tricky. Just let me know where to aim my contributions once you decide

**Pull request merged**
